[package]
name = "serde-json-build-example"
version = "0.1.0"
authors = ["Nick Fagan <nfagan@dal.ca>"]
edition = "2018"

[build-dependencies]
serde = { version = "^1.0.126", features = ["derive"] }
serde_json = "^1.0.64"
